latents: /work/vb21/haochen/neurips_2026/ImagenFew/logs/vae_latents/finetune_dataset/AirQuality_mu.pt
output_dir: /work/vb21/haochen/neurips_2026/ImagenFew/logs/diffusion_prior/dit1d_base_finetune/AirQuality
resume: null
resume_ckpt: null
finetune_ckpt: /work/vb21/haochen/neurips_2026/ImagenFew/logs/diffusion_prior/dit1d_base/diffusion_prior_best.pt
seed: 0
device: cuda
wandb: true
wandb_project: diffusion-prior
wandb_name: dit1d_base_finetune_airquality
wandb_tags: [dit1d, base, finetune, AirQuality]

epochs: 2000
batch_size: 2048
num_workers: 0
learning_rate: 0.0001
weight_decay: 0.00001
val_ratio: 0.0
save_every: 200

hidden_size: 512
depth: 8
num_heads: 8
mlp_ratio: 4.0
use_qknorm: false
no_rmsnorm: false

path_type: Linear
prediction: velocity
loss_weight: null
time_dist_type: 'logit-normal_0.0_1.0'
time_dist_shift: 1.0
ema_decay: 0.9999
