# training:
epochs: 1001
batch_size: 512
learning_rate: 0.0001
weight_decay: 0.00001

# transform:
use_stft: false
delay: 16
embedding: 16

# model:
handler: models.ImagenFew.handler
img_resolution: 16
unet_channels: 32
ch_mult: [1,2,2,4]
attn_resolution: [16,8,4]
diffusion_steps: 36
ema: true
ema_warmup: 100

# logging:
logging_iter: 100
tags: []
run_dir: ImagenFew/glucose_npy/

# Data
datasets_dir: ./data/
seq_len: 128
pretrain: false
datasets:
  - name: AIREADIGlucose
    data: npy_ts
    rel_path: glucose
    scale: true
train_on_datasets:
  - AIREADIGlucose
