epochs: 5001
batch_size: 512
learning_rate: 0.001
min_lr: 1.0e-05
weight_decay: 1.0e-05
warmup_steps: 500
gradient_accumulation_steps: 1
resume_ckpt: null
ema: true
ema_warmup: 0
ema_decay: 0.9999
handler: models.text_conditional_generator.handler
seq_len: 24
cond_dim_in: 2048
cond_dim_out: 128
caption_embeddings_path: ./logs/finetune_captions/ETTh2/train_caption_embeds.pt
pretrain_path: ""
prior_ckpt: null
sample_source: posterior
eval_metrics:
  - disc
  - contextFID
  - pred
metric_iteration: 10
diffusion:
  channels: 128
  n_scales: 3
  num_steps: 50
  beta_start: 0.0001
  beta_end: 0.5
  schedule: quad
  diffusion_embedding_dim: 128
  nheads: 8
  layers: 10
  multipatch_num: 3
  base_patch: 3
  L_patch_len: 2
  condition_type: adaLN
  n_stages: 5
  side:
    seq_len: 24
    var_emb: 16
    time_emb: 128
logging_iter: 100
no_test_model: true
tags:
  - text-conditional-generator
  - caption
  - ETTh2
run_dir: text_conditional_generator/from_scratch/ETTh2_caption
datasets_dir: ./data/
pretrain: false
datasets:
  - name: ETTh2
    data: ETTh2
    embed: timeF
    rel_path: TSF/ETT-small/ETTh2.csv
    features: M
    label_len: 7
    pred_len: 0
train_on_datasets:
  - ETTh2
