# training:
epochs: 1001
batch_size: 1024
learning_rate: 0.0001 #1e-4
weight_decay: 0.00001 #1e-5

# transform:
use_stft: false
delay: 8
embedding: 8

# model:
handler: models.ImagenFewCrossAttention.handler
model_ckpt: "./logs/conditional_pretrain/27dda8d2-003b-497b-a85d-c462dda27a79/ImagenFewCrossAttention.pt"
img_resolution: 8
unet_channels: 32
ch_mult: [1,2,2,4]
attn_resolution: [8,4,2]
diffusion_steps: 36
ema: true
ema_warmup: 100
ft_method: all

# conditioning:
#pretrained_vae_weights: "/work/vb21/haochen/neurips_2026/ImagenFew/logs/vae_pretrain/52131940-4465-42cb-85b4-93bd7f5ee944/MultiScaleVAE_Epoch330"
pretrained_vae_weights: "./logs/vae_pretrain/52131940-4465-42cb-85b4-93bd7f5ee944/MultiScaleVAE"
multi_scale_vae:
  z_channels: 64
  ch: 64
  ch_mult: [1, 2, 4]
  dynamic_size: 64
  dropout: 0.0

# logging:
logging_iter: 20
tags: [conditional-finetune, cross-attention]
run_dir: CondImagenFewFinetune/mujoco/

# Data
datasets_dir: ./data/
seq_len: 24
pretrain: false
datasets:
  - data: mujoco
    name: mujoco
    path: ./TSG/mujoco0.0
train_on_datasets:
  - mujoco
