# training:
epochs: 1001
batch_size: 128
learning_rate: 0.0001
weight_decay: 0.00001

# transform:
use_stft: false
delay: 24
embedding: 24

# model:
handler: models.ImagenFewCrossAttention.handler
img_resolution: 32
unet_channels: 32
ch_mult: [1,2,2,4]
attn_resolution: [16,8,4]
diffusion_steps: 36
ema: true
ema_warmup: 100
ft_method: all

# conditioning:
verbalts_context_suffix: long_clip

# logging:
logging_iter: 100
tags: [conditional-pretrain, cross-attention, verbalts, longclip]
run_dir: CondImagenFewScratch/VerbalTS_BlindWays_longclip/

# Data
datasets_dir: ./data/
seq_len: 600
pretrain: true
eval_split: train
datasets:
  - name: BlindWays
    data: verbal_ts
    rel_path: VerbalTSDatasets/BlindWays
train_on_datasets:
  - BlindWays
