epochs: 1001
batch_size: 256
learning_rate: 0.0001
min_lr: 1.0e-05
weight_decay: 1.0e-05
warmup_steps: 500
resume_ckpt: null
ema: true
ema_warmup: 0
ema_decay: 0.9999
handler: models.conditional_generator.handler
seq_len: 24
cond_dim_in: 64
cond_dim_out: 128
pretrain_path: ./logs/self_conditional_generator/pretrain/2133314a-ddb0-4f5f-b1eb-f0de9beb101a/conditional_generator.pt
pretrained_vae_weights: ./logs/vae_pretrain/52131940-4465-42cb-85b4-93bd7f5ee944/MultiScaleVAE
prior_ckpt: ./logs/diffusion_prior/time_shift_sweep/ETTh2/tds_1p0/diffusion_prior_latest.pt
prior_use_ema: true
posterior_train_mode: clean
posterior_train_alpha: 0.0
sample_source: both
sampler:
  mode: ODE
  params:
    sampling_method: dopri5
    num_steps: 50
    atol: 1.0e-06
    rtol: 0.001
    reverse: false
diffusion:
  channels: 128
  n_scales: 3
  num_steps: 50
  beta_start: 0.0001
  beta_end: 0.5
  schedule: quad
  diffusion_embedding_dim: 128
  nheads: 8
  layers: 10
  multipatch_num: 3
  base_patch: 3
  L_patch_len: 2
  condition_type: adaLN
  n_stages: 5
  side:
    seq_len: 24
    var_emb: 16
    time_emb: 128
multi_scale_vae:
  z_channels: 64
  ch: 64
  ch_mult:
  - 1
  - 2
  - 4
  dynamic_size: 64
  dropout: 0.0
logging_iter: 100
tags:
- self-conditional-generator
- clean
run_dir: self_conditional_generator/finetune/ETTh2_clean
datasets_dir: ./data/
pretrain: false
datasets:
- name: stock
  data: stock
- name: energy
  data: energy
- name: ETTh1
  data: ETTh1
  embed: timeF
  rel_path: TSF/ETT-small/ETTh1.csv
  features: M
  label_len: 7
  pred_len: 0
- name: Exchange
  data: custom
  embed: timeF
  rel_path: TSF/exchange_rate/exchange_rate.csv
  features: M
  label_len: 8
  pred_len: 0
- name: MSL
  data: MSL
  rel_path: MSL
- name: PSM
  data: PSM
  rel_path: PSM
- name: SMAP
  data: SMAP
  rel_path: SMAP
- name: SMD
  data: SMD
  rel_path: SMD
- name: SelfRegulationSCP2
  data: UEA
  rel_path: UEA/SelfRegulationSCP2
- name: UWaveGestureLibrary
  data: UEA
  rel_path: UEA/UWaveGestureLibrary
- name: ECG5000
  data: UEA
  rel_path: UEA/ECG5000
- name: NonInvasiveFetalECGThorax1
  data: UEA
  rel_path: UEA/NonInvasiveFetalECGThorax1
- name: Blink
  data: UEA
  rel_path: UEA/Blink
- name: ElectricDevices
  data: UEA
  rel_path: UEA/ElectricDevices
- name: Trace
  data: UEA
  rel_path: UEA/Trace
- name: FordB
  data: UEA
  rel_path: UEA/FordB
- name: EMOPain
  data: UEA
  rel_path: UEA/EMOPain
- name: Chinatown
  data: UEA
  rel_path: UEA/Chinatown
- name: SharePriceIncrease
  data: UEA
  rel_path: UEA/SharePriceIncrease
- name: ETTh2
  data: ETTh2
  embed: timeF
  rel_path: TSF/ETT-small/ETTh2.csv
  features: M
  label_len: 7
  pred_len: 0
train_on_datasets:
- ETTh2
